micronaut:
  application:
    name: demoMicronaut
  server:
    port: 8000
    cors:
      enabled: true

      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "TOP_SECRET_TOP_SECRET_TOP_SECRET_TOP_SECRET_TOP_SECRET_TOP_SECRET_TOP_SECRET"
datasources:
  default:
    url: jdbc:mysql://localhost:3306/test?generateSimpleParameterMetadata=true&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: click123
    dialect: MYSQL
    schema-generate: CREATE_DROP

netty:
  default:
    allocator:
      max-order: 3
